### ISSUE TITLE
Reconsidering async only

### ISSUE THREAD

**Issue by ehsanf** [Refty/bubble-client#5]
I was just trying to follow the examples in the readme and on python 3.10 I am getting this error:

SyntaxError: 'async for' outside async function

Overall, having support for async I/O is useful, but it can also get in the way as it is harder to debug and test with async I/O (or maybe I am not proficient in it). Can I suggest that we change the library so that it offers both a standard consumer API class and async I/O version would be an additional option that can be used?

Or maybe update the readme to have better examples.

**Comment by ramnes** [comment]
> I was just trying to follow the examples in the readme and on python 3.10 I am getting this error:
> 
> SyntaxError: 'async for' outside async function

It's because the default Python interpreter doesn't run an eventloop. Just use IPython or run `python -m asyncio`.

> Overall, having support for async I/O is useful, but it can also get in the way as it is harder to debug and test with async I/O (or maybe I am not proficient in it). Can I suggest that we change the library so that it offers both a standard consumer API class and async I/O version would be an additional option that can be used?

This is out of scope for our company right now. All the Python we write is async so we don't have any interest in adding a synchronous client. I'm personally quite used to projects that support both sync and async (i.e. I'm the author of [notion-sdk-py](https://github.com/ramnes/notion-sdk-py), for example) and frankly, it's a pain to support both, Python hasn't been designed for this.

> Or maybe update the readme to have better examples.

PR welcome! Happy to merge anything that helps newcomers.
